# Generated by Django 4.0.1 on 2022-01-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rahul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=20),
        ),
    ]
